In [19]:

#Num py exercises array ,datatypes
import numpy as np
a = np.array([1, 2, 3,4,5])
print(a)
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
(5,)
int32


In [20]:
#
b = np.array([[0, 2, 4,6], [1, 3, 5,6]])
print(b)
print(b.shape)
print(b.dtype)

[[0 2 4 6]
 [1 3 5 6]]
(2, 4)
int32


In [21]:
np.zeros(9)


array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(shape=(5, 7), dtype=np.int32)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [23]:
c = b * 2
print(c)
print(c.shape)
print(c.dtype)

[[ 0  4  8 12]
 [ 2  6 10 12]]
(2, 4)
int32


In [25]:
d = a + c
print(d)

ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [26]:
d[0]

array([1., 3., 5.])

In [27]:

d[0, 0]

1.0

In [28]:

d.sum()

19.5

In [30]:

d.mean()

3.25

In [31]:
d.sum(axis=0)

array([ 2.5,  6.5, 10.5])

In [32]:
d.mean(axis=1)

array([3. , 3.5])

In [15]:

e = np.arange(12)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# f is a view of contents of e
f = e.reshape(3, 4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# Set values of e from index 5 onwards to 0
e[5:] = 0
print(e)

[0 1 2 3 4 0 0 0 0 0 0 0]


In [18]:

# f is also updated
f

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])